### ISSUE TITLE
Sharpening borders a regression?

### ISSUE THREAD

**Issue by ya-d** [Ubuntu/gtk-communitheme#217] opened 2018-03-01 21:11 UTC
I'm still not really sure about my personal opinion but I wanted to repeat it here for discussion (don't know if anyone still looks into #209 #192):

* The new sharpening makes the border really pop and stand out. Maybe it draws too much attention? (Looks a bit like an oversharpend image: impressive at first, unnaturally popping at second glance.) Can it be scaled back a bit?
* [jagger](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/600): Makes other elements in the headerbar looking "too flat".
* Against bright backgrounds the corner looks too soft compared to the straight edges and rather pixelated too. (Don’t remember if that has been the case before though…)
* Especially the sharpening of the inner borders seems a regression to me. See vertically separating lines as most prominent example.
* Rest of the window has no "border".

//edit: Zoom in to see it more clearly.
<img width="269" alt="window border soft corner" src="https://user-images.githubusercontent.com/30781876/36869881-8ab053e0-1d9d-11e8-8846-d180d9a12da3.png">

//edit2: But great that it fixes windows melting with top bar when touching it! 🎉 Can't find the bug for that to reference.

**Comment by clobrano** [comment] 2018-03-01 22:20
> Especially the sharpening of the inner borders seems a regression to me. See vertically separating lines as most prominent example.

This wasn't intentional

> Against bright backgrounds the corner looks too soft compared to the straight edges and rather pixelated too. (Don’t remember if that has been the case before though…)

Before it was all blurry

**Comment by ya-d** [comment] 2018-03-02 07:34
I see. Than the change of the separating line between top bar and maximized windows wasn't intended either? I add it here as another thing to fix:
![6045e238dffb392f7e60a013123d3cc2dce0d845](https://user-images.githubusercontent.com/30781876/36888127-6fbbf27c-1df4-11e8-85a7-c4c44d396e02.png)
[(Screenshot by jyaku)](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/599)

**Comment by clobrano** [comment] 2018-03-02 07:56
There are two lines between panel and windows now. 

The grey one is by design and it is there since some releases (more or less, since panel acquired the same color as headerbar's).

The darker one is a side effect of another bug fix (I'm on the phone, I will reference the issue in a next update). We can try to remove it in maximised state

**Comment by clobrano** [comment] 2018-03-02 09:11
> I'm still not really sure about my personal opinion but I wanted to repeat it here for discussion

This discussion here is OK since it brought up other issues, but in general I'd prefer not to repeat discussions, the risk is to lose comments and make confusion

**Comment by clobrano** [comment] 2018-03-08 22:09
@Luxamman any thought about that?

**Comment by clobrano** [comment] 2018-03-19 08:11
Ok, closing this now, feel free to re-opening in the future

**Closed by clobrano** 2018-03-19 08:11 UTC
