### ISSUE TITLE
Black background in some apps

### ISSUE THREAD

**Issue by yawzub** [ubuntu/gtk-communitheme#243] opened 2018-03-08 19:02 UTC
Gnome Videos, Gnome Photos, Gnome boxes are affected.
![bg1](https://user-images.githubusercontent.com/36858800/37170577-3df0c100-231c-11e8-98ed-a140deb0dda3.png)

**Comment by clobrano** [comment] 2018-03-08 19:20
Those application are designed to be used with a dark variation, it's not due to the theme

**Comment by yawzub** [comment] 2018-03-08 19:56
@clobrano I'm talking about this #0b0b0d background. Is it intended?
![bg2](https://user-images.githubusercontent.com/36858800/37172971-6fcf2106-2323-11e8-8416-d3e21b59883b.png)
Shouldn't it be something like this instead?
![bg3](https://user-images.githubusercontent.com/36858800/37173115-c4cb547c-2323-11e8-8d79-37ec4e79c971.png)

**Comment by clobrano** [comment] 2018-03-08 21:21
oh I see now, thank you for reporting it :+1: 

However, mine is correct
 
![image](https://user-images.githubusercontent.com/2883614/37177145-e59f8970-231e-11e8-9d59-485b14fd6090.png)

**Comment by yawzub** [comment] 2018-03-09 04:30
@clobrano It turns black when you add something.
![bg4](https://user-images.githubusercontent.com/36858800/37190540-6bc86c82-236b-11e8-8ff4-21d83371675a.png)
![bg5](https://user-images.githubusercontent.com/36858800/37190547-700f39e2-236b-11e8-8478-ce9137b7f0d2.png)

**Comment by Feichtmeier** [comment] 2018-03-20 22:40
Is this really an issue? Adwaita uses the dark background, too:

![screenshot from 2018-03-20 23-39-37](https://user-images.githubusercontent.com/15329494/37686492-058999ec-2c98-11e8-976d-090d7e91e656.png)

**Comment by madsrh** [comment] 2018-03-21 10:12
Hmm, I'm not sure here. For reference I'll use Adwaita screenshots.

For the empty _(Stared photos will appear here)_ ["Favorites" background](https://user-images.githubusercontent.com/36858800/37190540-6bc86c82-236b-11e8-8ff4-21d83371675a.png) we can leave this as it is or change it to match "Photos" background (see below). I would say, leave it although it's currently a different color than the other views (photos/albums), but so is it in Adwaita.

This one is weird:
![1](https://user-images.githubusercontent.com/3986894/37703261-5a55a058-2cf5-11e8-94c1-3c5ab4076a79.jpg)
Three different background colors is too much. Let's change the #0b0b0d to black so we have one continuous background.

Photos:
![2](https://user-images.githubusercontent.com/3986894/37703504-29529442-2cf6-11e8-90d3-b0ec28586fa8.jpg)
To me, the "Photos" view looks really messy by design! I would suggest making the border match the background as seen in the Arc, Pop and Numix themes.

**Comment by clobrano** [comment] 2018-06-05 20:48
Hey @Feichtmeier, is this one fixed with your recent work on dark variant?

**Comment by Feichtmeier** [comment] 2018-06-05 21:57
Well at least videos is "affected":
![image](https://user-images.githubusercontent.com/15329494/41005010-09217082-691c-11e8-96c1-f47944603690.png)
(Yeah that's my headbanging daughter)
But are you sure this should be changed? This way it looks like a real "movie" background. :man_shrugging:

**Comment by clobrano** [comment] 2018-06-06 07:11
Double checked now, it looks like the last suggestion from @madsrh isn't implemented

> EDIT: I actually think the current very discreet border between photos is nice. My initial thought was to make the border match the background (black) as seen in the Arc, Pop and Numix themes.

do you think this is possible?

**Comment by Feichtmeier** [comment] 2018-06-06 13:50
![image](https://user-images.githubusercontent.com/15329494/41041940-b6afaa50-69a0-11e8-8026-7bc9bfe5e3f3.png)
![image](https://user-images.githubusercontent.com/15329494/41042033-ed6ef546-69a0-11e8-84aa-c041e9ebe45a.png)
.documents-scrolledwin.frame.frame widget flowboxchild.tile  { background-color: transparent; }
@clobrano @madsrh 
Fixed it for Photos. I think there is only that background in photos. Videos has no background (anymore)
I could make a PR for photos.

Or, if you want the border to have the same color:
![image](https://user-images.githubusercontent.com/15329494/41042190-4bd1a818-69a1-11e8-9d56-8ddd037a7e46.png)
![image](https://user-images.githubusercontent.com/15329494/41042210-56d28610-69a1-11e8-886a-800825ffe848.png)

**Comment by Feichtmeier** [comment] 2018-06-06 14:04
My personal fav would be transparent background:
![lo](https://user-images.githubusercontent.com/15329494/41042992-429349e4-69a3-11e8-96b6-5f1189e6a579.gif)

**Comment by clobrano** [comment] 2018-06-06 16:09
Thanks @Feichtmeier, I prefer transparent as well :+1:

**Comment by Feichtmeier** [comment] 2018-06-06 16:27
Cool I just realized that gnome boxes is already fixed so photos is the only left

**Closed** 2018-06-06 17:01 UTC
Labels: confirmed, design
