### ISSUE TITLE
Issues with GIMP dark theme

### ISSUE THREAD

**Issue by giovannicaligaris** [ubuntu/gtk-communitheme#512] opened 2018-06-04 18:10 UTC
Just installed GIMP 2.10 on Ubuntu 18.10 using the SNAP version of communitheme. There seems to be an issue with any of the themes, something is breaking.

I have gtk2-engines-pixbuf installed.

![screenshot from 2018-06-04 19-06-11](https://user-images.githubusercontent.com/26255347/40933815-9dd3c376-682a-11e8-90fa-bb87f6abfd6d.png)

**Comment by clobrano** [comment] 2018-06-05 14:29
> There seems to be an issue with any of the themes, something is breaking.

Do you mean that this is reproducible with Adwaita and Ambiance as well?

**Comment by Paz-it** [comment] 2018-06-06 16:00
@giovannicaligaris did you install the snap app or the.deb?

**Comment by Feichtmeier** [comment] 2018-06-06 16:06
![image](https://user-images.githubusercontent.com/15329494/41050634-41ad1c56-69b4-11e8-8fe6-cabc149f31ca.png)

I don't have this issue with both communitheme and gimp installed as a snap in my VM

**Comment by giovannicaligaris** [comment] 2018-06-07 13:05
I installed the deb

**Comment by clobrano** [comment] 2018-06-07 20:53
I cannot reproduce this either. I installed GIMP with both ppa and flatpak and everything seems OK

**Comment by mivoligo** [comment] 2018-06-08 09:04
Turns out I have the same issue. Installed from flatpak.
![zrzut ekranu z 2018-06-08 10-03-55](https://user-images.githubusercontent.com/1629120/41149384-4f88aeda-6b03-11e8-8755-4f6151e96bf0.png)

**Comment by clobrano** [comment] 2018-06-08 09:29
This is weird

**Comment by mivoligo** [comment] 2018-06-08 09:35
What's even weirder: I've installed it few weeks ago via GIMP website. Problem is I don't know how to remove it now because it does not appear in the Software Center as installed :-/

**Comment by clobrano** [comment] 2018-06-08 09:38
it should be something like `flatpak remove com.org.GIMP`

**Comment by Feichtmeier** [comment] 2018-06-08 09:38
Okay guys:
- freshly installed ubuntu without touching anything
- freshly installed communitheme -> reboot -> session select
- freshly installed gimp snap
-> this is not reproducible, sorry.

**Comment by Paz-it** [comment] 2018-06-08 09:47
Did you noticed @giovannicaligaris  is talking about Ubuntu 18.10?

**Comment by Feichtmeier** [comment] 2018-06-08 09:49
My VM is 18.10!

**Comment by mivoligo** [comment] 2018-06-08 10:04
I've removed flatpak version (thanks @clobrano) and installed snap version. The issue is no longer here for me.

**Comment by Feichtmeier** [comment] 2018-06-09 15:54
We still don't know if this only happened with communitheme :man_shrugging:

**Comment by Paz-it** [comment] 2018-06-09 22:45
For me it is only in Ubuntu snap but not only with communitheme. 
When logging in to Ubuntu all is well with Dark Gimp. (Adwaita-Dark).

**Comment by Paz-it** [comment] 2018-06-10 03:31
This might be still the problem to those who install the ,deb. 
I just the workaround command and it also solved my synaptic not being themed.
https://github.com/ubuntu/gtk-communitheme/issues/358

**Comment by clobrano** [comment] 2018-06-10 06:27
Weird, the workaround should already be in master

**Comment by Paz-it** [comment] 2018-06-10 11:44
Weird indeed! - Maybe @didrocks  can help us out in this confusion?

**Comment by didrocks** [comment] 2018-06-11 08:02
I guess ensure you don't have the communitheme deb, but only the snap, and any local version of communitheme installed manually on the system. As this isn't reproducible on a fresh system, it's probably an user configuration due to some of this on the impacted system

**Comment by clobrano** [comment] 2018-06-11 11:29
Closing this then

**Closed by clobrano** 2018-06-11 11:29 UTC
Labels: info-needed

**Comment by Paz-it** [comment] 2018-06-13 20:28
@clobrano ,
I see @didrocks reply only now. In my case there is no deb of communitheme on my system but it is an upgraded 18.04 from 17.10 32 bit so maybe there is something like that but I don't know where to look for the culprit. any suggestions? Thanks!
