### ISSUE TITLE
Title bar icon look ugly in gnome terminal

### ISSUE THREAD

**Issue by Mofiqul** [ubuntu/gtk-communitheme#606] opened 2018-07-05 11:07 UTC
Today after I update my system the title bar icon for the gnome-terminal looks ugly and misplaced. I am attaching a screenshot 
[Screenshot](https://imgur.com/f6JVEes)

**Comment by Feichtmeier** [comment] 2018-07-05 23:29
Hi! Some questions arise when looking at your screenshot:

- is this the communitheme from this repository?
- if yes, what did you modify
- is that gnome-terminal?
- you switched the app menu to the left, right?

**Comment by CDrummond** [comment] 2018-07-06 12:22
I can confirm that the above screenshot occurs in gnome-terminal, using latest git/master of communitheme, when the tweaks is used to configure the top bar to **not** show the application menu. I can see the same issue with the menu-button on right hand side of titlebars.

I know this is not a default GNOME setup (as the mentioned setting needs to be toggled), but (AFAIK) the intention is to remove this application menu in future GNOME releases.

**Comment by Mofiqul** [comment] 2018-07-06 16:35
+ is this the communitheme from this repository?
>Yes, Installed using snap from edge channel
+ if yes, what did you modify
>Nothing. I am so much happy with its default 😊. 
+ is that gnome-terminal?
>Yes
+ you switched the app menu from the right to left
>Title bar buttons? Yes, and  I turned off the application menu for the top bar that causes it. When I turn on application menu it's fine. 

Shell theme I am using [Unity8](https://github.com/unc926/Unity8)

**Comment by Feichtmeier** [comment] 2018-07-06 20:59
Since the server side decorations are made by mutter would be interesting to see if this also happens with the communitheme shell theme. Could you check that please @Mofiqul

**Comment by Feichtmeier** [comment] 2018-07-07 06:16
So this is a fresh virtual machine within the communitheme session with the app menu in the title bar and all buttons to the left:
![image](https://user-images.githubusercontent.com/15329494/42407505-1271a0fc-81be-11e8-85ff-7bc5dfa1f17c.png)

**Comment by Mofiqul** [comment] 2018-07-07 07:02
Yes, it's reproduced with communitheme shell them also when the application menu is off. And one more thing that in the top right the icons of shell extensions too far then it should be i thing. Here is the [screenshot](https://imgur.com/epaCvMX)

**Comment by clobrano** [comment] 2018-07-07 16:42
Something does not look right, why the black dockbar?

**Comment by clobrano** [comment] 2018-07-08 19:17
Confirmed now, but it's an upstream bug already on launchpad [1770507](https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1770507). Closing this.

**Closed by clobrano** 2018-07-08 19:17 UTC
Labels: confirmed, upstream
