### ISSUE TITLE
An additional orange vertical line in Eye of GNOME to the right of the zoom percentage entry widget when the widget is focused

### ISSUE THREAD

**Issue by slackmate** [Ubuntu/gtk-communitheme#196] opened 2018-02-24 08:06 UTC
There is an additional orange vertical line in Eye of GNOME (image viewer) to the right of the zoom percentage entry widget when the widget is in focus. It seems to be at the border of the zoom-in button.

![zoom-selector](https://user-images.githubusercontent.com/30923711/36627354-bfa37362-1941-11e8-8824-39e2a4600023.png)

**Comment by clobrano** [comment] 2018-02-24 09:39
This looks like a duplicate of #68

**Comment by slackmate** [comment] 2018-02-24 10:48
On closer inspection it definitely is not a vertical line but the highlight of the zoom-in button. So this might be the same issue. Good catch!

**Closed** 2018-02-24 13:27 UTC
