### ISSUE TITLE
Private Internet Access tray icon missing

### ISSUE THREAD

**Issue by markolo25** [ubuntu/gtk-communitheme#441] opened 2018-05-14 02:47 UTC
Hello, when using communitheme snap package the tray icon for Private Internet Access client is missing, and comes back when using the default Ubuntu theme.

**Comment by clobrano** [comment] 2018-05-14 11:26
Hi @markolo25, thank you for reporting this.
I don't have a VPN (I guess this is what you mean), so I'd like to know which client are you using, if you can specify it better, and if you're able to run it from the shell, so that we can see any debug/error log

**Comment by clobrano** [comment] 2018-05-18 13:25
Thanks @markolo25, now it is more clear. It looks like PIA client is made with electron, then this is a duplicate of https://github.com/ubuntu/gnome-shell-communitheme/issues/95 
A fix has been already merged upstream, so we need to wait next electron version, then PIA should include this new version to have your bug fixed.

**Closed by clobrano** 2018-05-18 13:25 UTC
Labels: info-needed, snap
