### ISSUE TITLE
Calculator is unthemed

### ISSUE THREAD

**Issue by koma111** [ubuntu/gtk-communitheme#426] opened 2018-05-10 20:39 UTC
On Ubuntu 18.04, using the Communitheme session (fresh install), gnome-calculator is unthemed. On some installs, it simply appears with the Ambiance theme, while on others the app appears without any theming, with every element being transparent, every text and icon white, no paddings or borders, as if everything were set to 'transparent' or '0'. When I open GTK Inspector for the Calculator app, Communitheme does not show up among GTK themes. This is a serious issue as Calculator is a crucial utility.
![virtualbox_bionic_10_05_2018_22_37_26](https://user-images.githubusercontent.com/32468934/39893097-06083e18-54a3-11e8-894a-b7fa1262756c.png)

**Comment by Feichtmeier** [comment] 2018-05-10 23:33
HI @koma111 thanks for contributing
Sadly I will close this for two reasons:

1) the transparent part is a snap problem and fixed (now or soon for you)
2) that ambiance is working and communitheme is not is caused by communitheme not yet included in the gtk-common snap but it will be soon be fixed

You can find both issues in the issue list in either closed or opened
Best regards

**Closed by Feichtmeier** 2018-05-10 23:33 UTC
