### ISSUE TITLE
inactive window switch does not clearly show its on/off state

### ISSUE THREAD

**Issue by fthx** [ubuntu/gtk-communitheme#238] opened 2018-03-08 07:25 UTC
Hi,

When I try to add a search engine : 
![image](https://user-images.githubusercontent.com/23138504/37138364-1fa7b0c2-22aa-11e8-82d3-eea80e64baa1.png)
the "Default" button should be green.

**Comment by fthx** [comment] 2018-03-08 07:28
ok, it seems that the bug lies in Epiphany as Ambiance or Adwaita do show the same behaviour.
BUT these two themes show I O and Communitheme does not, which renders the button state questionable.

**Comment by Feichtmeier** [comment] 2018-03-08 21:41
What do you mean with IO (input output - but where? what?) 
And if this issue is not related to this theme, I guess it would be good if you close it again :)

**Comment by fthx** [comment] 2018-03-08 21:49
I wrote I O, not IO... Simply look at the Ambiance or Adwaita switches.

And *I* will not close this issue since, whatever Epiphany is buggy, an inactive window switch state is questionable running Communitheme.
E.g., look at my Tweak window while I'm reading the email notification in Evolution.
![image](https://user-images.githubusercontent.com/23138504/37178423-c2c952d8-2322-11e8-803a-40e2f21638df.png)

The switches of Adwaita/Ambiance do show clearly what's the switch state is, not Communitheme.

**Comment by clobrano** [comment] 2018-03-08 21:50
I think the problem is Epiphany adding "insensitive" class to the switcher when checked

![image](https://user-images.githubusercontent.com/2883614/37178456-d4d86072-2322-11e8-8045-26df49dbad22.png)

maybe because one cannot uncheck the default engine

**Closed** 2018-06-07 21:47 UTC
Labels: enhancement
