### ISSUE TITLE
Change background colour of menu titles

### ISSUE THREAD

**Issue by ubuntujaggers** [ubuntu/gtk-communitheme#391] opened 2018-05-01 21:06 UTC
Creating an issue at the request of @madsrh.

Two options are under discussion:

- Tweak the grey to be the shade currently used for the out-of-focus window header bar (reasoning and mock-ups are in https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/960?u=jaggers - I believe this is @madsrh's preferred approach).

- Remove the separating line and make header bar/menu titles the same colour, so they combine to form a single continuous area.  @clobrano has said that this is possible, and some thread contributors prefer this approach.

**Comment by madsrh** [comment] 2018-05-01 21:26
## Illustration of the contrast tweak
_View_, _Layer_ and _Object_ have the proposed background colour, whereas _Path_, _Text_ and _Filters_ have the current background colour:
![image](https://user-images.githubusercontent.com/3986894/39494432-a7f1967a-4d96-11e8-99fd-edc058b1723b.png)

## Remove the separating line and continuous color
![image](https://user-images.githubusercontent.com/3986894/39494493-e76a8a32-4d96-11e8-8e33-6857503a0c2a.png)

**Comment by Feichtmeier** [comment] 2018-05-01 21:31
Has the white idea been completely rejected?
Other than that I'd prefer the first option

**Comment by madsrh** [comment] 2018-05-01 21:37
@Feichtmeier I think so #281 IMO "the big block of darkness" 😆 returns with option two above, so I vote for option one. 
I'm really excited to hear what @godlyranchdressing and @clobrano think about this 👀

**Comment by Ads20000** [comment] 2018-05-01 22:07
Personally I like the second option. The menus should seem like they're part of the title bar since with CSD apps they actually are part of the title bar... White could make sense since the menus are more about the application than the shell (white for applications and black for the shell?) but since the CSD menus are black buttons (and white menus, as with the current menu bar) maybe the menu bar should also be black, which would mean that the second option is idea... That said, menu bars are effectively depreciated under GNOME, so 'demoting' them by giving them a more grey background (making it less merged with the title bar) may make sense...

**Comment by chrisjbillington** [comment] 2018-05-02 00:52
Since you can even click and drag on empty space in the menu bar to move the window (not if you click on one of the actual menus though), it is behaving much like CSD embedded in the title bar, so it makes sense for it to be visually very similar, and probably even identical (i.e. the continuous colour option). If it was any other colour or if there were a dividing line, would you know you could click and drag on it?

**Comment by clobrano** [comment] 2018-05-02 10:48
I am in favor of second option as well. I know that it might increase the "big block of black" 😄 , but I could not explain the usage of multiple lines with slightly different colors as well.
Moreover as someone (sorry I forgot who) already suggested, we could reduce titlebar size if we make it contiguous with menubar. Indirectly this will go along with a previous PR to reduce/remove titlebar in gtk dialogs

**Comment by madsrh** [comment] 2018-05-02 10:54
Alright @clobrano 👍 Did you just assign yourself to this issue? 😆

**Comment by Feichtmeier** [comment] 2018-05-02 17:51
@clobrano I am not sure about recuding the title bar height. Are the properties disconnected from the CSD header bars? If yes I would +1 this. Otherwise not, since the CSD header bar feel perfectly sized at the moment. 
(((I can only recommend to install https://extensions.gnome.org/extension/1267/no-title-bar/ for the non-CSD apps out there. I will open a topic to include this extension by default for 18.10.)))

**Comment by clobrano** [comment] 2018-05-03 07:42
> @clobrano I am not sure about recuding the title bar height

Yes, at the end of the day I am not as well. I tried a little, but I don't think I will push this change anymore

**Comment by CDrummond** [comment] 2018-05-03 07:49
The titlebar properties are (or should be) distinct from the headerbar. Ambiance, for example, has the same height headerbars as communitheme, but its titlebars are about 8pixels thinner than communitheme.

**Comment by clobrano** [comment] 2018-05-03 13:53
One problems are the window control buttons. If the titlebar is too small, also those button would be smaller in titlebar than in headerbars. Ambiance has very little window control buttons, but our goal was to keep them larger

**Comment by Feichtmeier** [comment] 2018-05-03 13:55
Yeah I think we should not try to fix problems that were created by the straight design of gnome. The problem is that gnome does not merge the bars by default. Only that extension can do this. So this is something that we need to discuss on the hub I guess

**Comment by CDrummond** [comment] 2018-05-03 16:17
I'm not sure what extension is going to blend a titlebar with menubar - this needs to be done in the theme. I assume you refer to the extension that removes the titlebar from maximized windows - but that is a different use case. What I'm discussing would be for all windows - maximized or not.

The current rounded buttons are already smaller, so should be relatively easy to reduce the height of the titlebar.

Anyway, this is not major issue - it was just a suggestion.

**Comment by Feichtmeier** [comment] 2018-05-03 17:40
Ofc I was talking about an extension that removes the titlebar! Merging was a little ... creative for what I've thought of ;O
But again: a theme should not be responsible for reducing gnome design decisions. We did not have this "problem" in unity7. But this is gnome so either install an extension or live with it. :[
If the size of the non-csd titlebars are drastically smaller it could look a bit awkward. They are in fact already smaller:
![image](https://user-images.githubusercontent.com/15329494/39593367-d0c75958-4f09-11e8-9d01-51285c46f73a.png)

**Comment by CDrummond** [comment] 2018-05-03 18:48
@Feichtmeier not sure what 'problem' you are referring to. There is no problem. With Ambiance the titlebar+menubar appear to blend together. As I think they should, as you can drag the window by either of these. I also think that the primary toolbar should also blend in - as you can also drag via here too. All IMHO. Now the second point was to make the titlebar a little thinner - as it is in Ambiance. This has nothing to do with Unity. You seem to be again mixing blending titlebar(of the window) + its menubar with the global menubar in Unity.

How is asking for the windows titlebar to be a little thinner going against GNOME design decisions? I fail to see the relevance.

Anyhow, I am fine with leaving as is - not trying to persuade or force my opinion on anyone. You just seem to be confusing issues.

**Comment by Feichtmeier** [comment] 2018-05-03 19:03
The blending is being addressed in that PR.
Yet you were also talking about reducing the titlebar of non-CSD windows -> which is, imho, a way to reduce the gnome design of having a top menu + title bar.
In unity you head the nautilus with unity pathes which would be a titlebar UPON the headerbar, but it was removed when you maximized it. In gnome you don't have the unity patches thus all gnome apps (95%) have no titlebar and all window controls in the headerbar. But when you got third party apps which don't provide client side decorations things get a bit weird and you have a tilebar upon the window:
![screenshot from 2018-05-03 21-02-19](https://user-images.githubusercontent.com/15329494/39597338-564b1b9a-4f15-11e8-8d77-8ebb95423caf.png)
With the extension:
![screenshot from 2018-05-03 21-02-19](https://user-images.githubusercontent.com/15329494/39597350-603fc574-4f15-11e8-9083-7b0df482cf35.png)

So saying "let's reduce the tilebar height" is a try to remove the gnome design "flaw". So I don't mix up anything here.

Titlebar =! headerbar

**Comment by CDrummond** [comment] 2018-05-03 20:42
@Feichtmeier I'm sorry if I've offended you, that was not my intention. I'll back out of this now, as its going round in circles. I know what a titlebar is, and how it is different to a headerbar. Again, I'm happy (not that it is in anyway my decision anyhow) for the titlebars to remain is - was only offering a suggestion. (My suggestion was not infact related to the topbar, more for non-maximised windows).

**Comment by Feichtmeier** [comment] 2018-05-03 20:44
You didn't - everything's fine here! :dancer:

**Closed** 2018-05-04 08:44 UTC
Labels: design-ok
