### ISSUE TITLE
Sidebar background colors change

### ISSUE THREAD

**Issue by yawzub** [ubuntu/gtk-communitheme#259] opened 2018-03-13 09:52 UTC
I'm sorry but can someone point me to a discussion about this change? Because I'm kinda confused. Previous version was better for me.
Before:
![before](https://user-images.githubusercontent.com/36858800/37334285-88148958-26bc-11e8-88b3-9c2558c7cb33.png)
After:
![after](https://user-images.githubusercontent.com/36858800/37334297-90dd694c-26bc-11e8-9415-48e24574fefc.png)

**Comment by clobrano** [comment] 2018-03-13 10:54
Change was intended to affect only sidebars to look like Nautilus. I'll look into the other applications

**Comment by fitojb** [comment] 2018-03-17 22:36
I agree; it seems to me that sidebars should be clearer than the application’s main background, even if it’s inconsistent with Nautilus. This change has made LibreOffice’s toolbars unusable, as there is no discernible distinction between a hovered toolbar button and the toolbar’s background.

**Comment by clobrano** [comment] 2018-03-18 09:30
@fitojb could you post an example of how the libreoffice's toolbar is unusable?

**Comment by fitojb** [comment] 2018-03-18 10:39
Can you tell which icon am I hovering in this screenshot?
![captura de pantalla de 2018-03-18 04-32-59](https://user-images.githubusercontent.com/554953/37564952-ca5856b2-2a65-11e8-9100-4c1bcf226034.png)

We’ve made previously gray buttons stand out from the similarly gray background, but now we’re back again with a contrast problem as the background was also brightened up. Both surfaces are supposed to have contrast! Look at the expander in Gnome Software, which I’m also hovering in this screenshot: 
![captura de pantalla de 2018-03-18 04-33-16](https://user-images.githubusercontent.com/554953/37564960-da2a9320-2a65-11e8-9429-388775117a26.png)

In both cases, the hovered button is pure white (#ffffff) and the background is #fdfdfd (!!!).

**Comment by clobrano** [comment] 2018-03-18 13:10
@fitojb I understand, but this has anything to do with the color change, it's a side effect of button restyling. I'm going to open a new bug for this

**Comment by fitojb** [comment] 2018-03-18 15:33
> @fitojb I understand, but this has nothing to do with the color change, it's a side effect of button restyling. I'm going to open a new bug for this

Um, nope, it has to do with this color change. The button restyling was perfectly fine before this color change.

**Comment by clobrano** [comment] 2018-03-18 17:00
If you look at the change it has nothing to do with toolbars, moreover I double checked taking the last commit before the sidebars and the problem you reported it's already there (in bionic).
I said it's a side effect of button changes because it's there that we used the same color for background and buttons, moreover buttons in toolbar are flat, that brought the absense of the borders. This is the first flat button I saw in a bright background, while usually are in the headerbar.

Anyway, this is not really important, it's a bug and will be fixed, thank you for reporting it :wink:

**Comment by fitojb** [comment] 2018-04-12 00:34
By now I have stopped using this theme because it’s too bright.

**Comment by clobrano** [comment] 2018-04-12 06:11
I'm sorry to hear that, but maybe discussing it on the forum would be more useful

**Comment by madsrh** [comment] 2018-05-07 10:58
I'm closing this issue. If anyone disagrees, let me know and I'll reopen it 👍

**Closed by madsrh** 2018-05-07 10:58 UTC
Labels: bug, confirmed
