### ISSUE TITLE
Suggestion: No side-bar/scrolbar vertical sepatator 

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/gtk-communitheme#507] opened 2018-06-02 05:43 UTC
I would like suggest  it since it looks cleaner in some apps.  if possible to make it in all apps instead.
Just a sample of logs,tweaks and nautilus : 
![screenshot from 2018-06-02 08-23-27](https://user-images.githubusercontent.com/37431503/40871259-094e9b6c-6641-11e8-9f38-2a0ffb8c0aaa.png)

**Comment by clobrano** [comment] 2018-06-02 16:08
This is actually a kind of regression I think. We use to have the same sidebar separation (not sure in logs, but in tweaks, settings and nautilus for sure). Nautilus is the one that's right a the moment, because sidebar line is the same as other lines in the same application (e.g. in list view, the lines in the table are the same). So we should bring the same line in the other application as well. Eventually, a little bit thinner

**Comment by Paz-it** [comment] 2018-06-03 01:53
Oh no... Sorry I brought it up :sob:  Please reconsider  :man_facepalming:

**Comment by clobrano** [comment] 2018-06-05 14:31
@Paz-it how would Nautilus look if there were some separation lines dark and some very pale? :)

**Comment by Feichtmeier** [comment] 2018-06-05 14:34
@Paz-it I disagree. Though I am probably the greatest "flat-enthusiast" when it comes to our shell theme, the border makes some sense in this half flat half skeuomorphistic (god that word...) theme. :)

**Comment by Paz-it** [comment] 2018-06-05 15:22
@clobrano , I'm talking ONLY about the vertical separator between the sidebar and the view area, that already separated by different color anyway. That one only bothers me :).
Good lord @Feichtmeier ! Skeomorphistic?!? :face_with_head_bandage: 
![faint](https://user-images.githubusercontent.com/37431503/40985739-6bf8c022-68ed-11e8-94df-e9a79f215431.gif)

**Comment by clobrano** [comment] 2018-06-05 15:45
That is what I'm talking about. Having only some lines visible and some not, doesn't look good to me

**Comment by Paz-it** [comment] 2018-06-06 12:53
@clobrano  we seems to agree. the only thing we might not is : 
I want to remove them all and you want to have theme all. did I understand you correctly?

**Comment by clobrano** [comment] 2018-06-06 16:14
Yes. My point of view is that Nautilus has (or might have, it depends on the view) several separation lines

![image](https://user-images.githubusercontent.com/2883614/41051077-6526e01c-69b5-11e8-9f96-d80aec39fa80.png)

Some time ago I made a change to make the sidebar separation very light (as you want), but correctly my team noted that it didn't make much sense with the other lines being a lot more visible

**Comment by Paz-it** [comment] 2018-06-07 03:54
@clobrano I understand the argument and agree there are too many lines visible. how about to it up a bit more? for example : 
Instead of the current - :  
![screenshot from 2018-06-07 06-23-27](https://user-images.githubusercontent.com/37431503/41077448-48898e04-6a1f-11e8-8bdb-781d014e6e7c.png)
It can be - : 
![screenshot from 2018-06-07 06-47-35](https://user-images.githubusercontent.com/37431503/41077464-6260f402-6a1f-11e8-97a9-cf838cbda54f.png)
What do think? may be worth a try?

**Comment by clobrano** [comment] 2018-06-07 06:41
@Paz-it it is a nice idea, however those vertical lines in table header do not look right this way, and without them the arrow that shows how the lines are sorted will be disconnected from the related label

**Comment by Paz-it** [comment] 2018-06-07 10:45
OK. it's about a different point of view. I don't think we need to emphasis so much by framing everywhere . a hint sometimes is enough.  it is very clear to me that these are columns with small separators and when pressing the arrow the color can change. the same with tabs. anyway, I've tried! :-)

**Comment by Feichtmeier** [comment] 2018-06-07 10:58
The problem in that search pic is the treeview header. It needs to have the same color as the table.

**Comment by clobrano** [comment] 2018-06-07 12:36
> OK. it's about a different point of view. I don't think we need to emphasis so much by framing everywhere.

I agree with that. We don't need to have a strong lines, but some lines are necessary, from my point of view.

**Comment by Paz-it** [comment] 2018-06-07 22:09
A good balance is the key word. 
Go out and look around the outstanding genus balance between color and functionality. The best in the world IMO. :+1:  :))

**Comment by clobrano** [comment] 2018-06-08 09:44
> Go out and look around the outstanding genus balance between color and functionality

What's genus?

**Comment by Paz-it** [comment] 2018-06-08 10:49
misspelled  for genius ! ...lol..

**Comment by clobrano** [comment] 2018-06-11 11:28
partially addressed by #532

**Closed** 2018-06-11 11:28 UTC
Labels: design
