### ISSUE TITLE
Issue with window corners in Firefox without titlebar

### ISSUE THREAD

**Issue by jim3872** [Ubuntu/gtk-communitheme#179] opened 2018-02-19 15:33 UTC

**Comment by jim3872** [comment] 2018-02-19 15:42
With the new version of firefox you can remove the title bar.  This causes issue with the window corners 
![screenshot from 2018-02-19 15-39-35](https://user-images.githubusercontent.com/36636462/36385776-75f0460a-158b-11e8-8c29-ffb82db564f0.png)

**Comment by madsrh** [comment] 2018-02-19 20:43
@jim3872 Thanks for reporting this issue. Do you know if this issue applies to other GTK themes as well, like [this bug](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/520)?

**Comment by jim3872** [comment] 2018-02-20 12:42
It does it too with united-Ubuntu-darker which has a similar title bar with the rounded corners.
![screenshot from 2018-02-20 12-40-16](https://user-images.githubusercontent.com/36636462/36424541-85a358d4-163b-11e8-92b1-f81a844c5880.png)

**Comment by clobrano** [comment] 2018-02-21 10:49
I changed the title to make it more descriptive

**Comment by jim3872** [comment] 2018-02-21 11:44
Thanks.
It looks like its ubiquitous with all themes with rounded corners, including the Pop OS theme

**Comment by Huluti** [comment] 2018-03-10 14:40
There is also a problem if we use a light theme : 

![capture du 2018-03-10 15-37-30](https://user-images.githubusercontent.com/5782198/37243425-4adcd0f8-2479-11e8-8b2f-1b6335973427.png)

**Comment by ya-d** [comment] 2018-03-11 15:50
This is a *beta* feature in *nightly builds* of Firefox. Any bugs are most likely not caused by this theme which is why I would vote to close this thread. Can be easily reopened if issues remain with stable builds and this theme alone.

Also see [omgUbuntu](https://www.omgubuntu.co.uk/2018/02/enable-firefox-csd-on-linux) that this are universal issues of Firefox.

**Comment by clobrano** [comment] 2018-03-12 08:07
As per @ya-d comment, any bug related to nightly build will be addressed in the future if still present in more stable versions

**Closed by clobrano** 2018-03-12 08:07 UTC

**Comment by Huluti** [comment] 2018-05-06 12:08
Things have changed:

Before:
![capture du 2018-03-10 15-37-30](https://user-images.githubusercontent.com/5782198/37243425-4adcd0f8-2479-11e8-8b2f-1b6335973427.png)

After:
![capture du 2018-05-06 14-06-23](https://user-images.githubusercontent.com/5782198/39673124-b5f9c406-5136-11e8-8f35-f17d63e88f25.png)

How the buttons are handled? Maybe they have a background color that could be transparent.

**Comment by clobrano** [comment] 2018-05-06 12:10
Hi @Huluti, we are trying this circular buttons, so I think the problem is actually the same as before

**Comment by Huluti** [comment] 2018-05-06 12:11
Hi @clobrano, yes but do there will be a solution to make these buttons looks correct when the headerbar is not dark?

**Comment by clobrano** [comment] 2018-05-06 12:13
Wasn't this a beta feature? How do you enable  it?

**Comment by Huluti** [comment] 2018-05-06 12:14
Not the theme, you can enable it in the theme manager.

**Comment by Huluti** [comment] 2018-05-06 12:15
But the problem is only visible when you enable the "CSD" beta feature of Firefox Nightly which remove the titlebar.

**Comment by Feichtmeier** [comment] 2018-05-06 14:55
The problem is that atm the circle is always drawn:
  &:not(.close) {
   
      @include draw_circle($c) ;
      &:backdrop:hover{@include draw_circle(darken($headerbar_fg_color,50%), $close:true)}
    
  }

When you change it to 

   &:not(.close) {
    &:hover {
      @include draw_circle($c) ;
      &:backdrop:hover{@include draw_circle(darken($headerbar_fg_color,50%), $close:true)}
    }
  }

Firefox-nightly looks like this (though you would have to change the whole theme to the firefox "light theme" to reproduce your issue, no idea if we want to got this far with this theme that we support custom skins in firefox):
![peek 2018-05-06 16-54](https://user-images.githubusercontent.com/15329494/39674583-422b8e34-514e-11e8-8666-fe3ab253fffe.gif)

**Comment by Feichtmeier** [comment] 2018-10-16 12:38
We removed the roundness of firefox. I don't know if firefox fixed the issue with the white border bleed :man_shrugging: 
If yes, we can remove the custom styling

**Comment by memeplex** [comment] 2019-06-09 02:17
Hey, despite the last comment and the issue having been closed this is still happening and has been recently reported to launchpad and confirmed: https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1828728

**Comment by memeplex** [comment] 2019-06-09 02:20
There might have been a regression in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1408360

**Comment by clobrano** [comment] 2019-06-09 06:25
Thanks @memeplex, but the last time we tried our tweak wasn't working anymore. We can try again, but as you saw it's a Firefox issue

**Comment by memeplex** [comment] 2019-06-09 12:56
Yes, fair enough, it seems Firefox will have this regression with every odd release :p

**Comment by memeplex** [comment] 2019-06-09 17:17
I see Adwaita-dark sets a dark color for the pointy edges, the problem is still there but it's less visible.

**Comment by memeplex** [comment] 2019-06-09 17:27
I've informed of the regression in every related closed issue and also opened a new issue https://bugzilla.mozilla.org/show_bug.cgi?id=1558065

**Comment by memeplex** [comment] 2019-09-15 11:01
@clobrano https://bugzilla.mozilla.org/show_bug.cgi?id=1408360#c38. What do you think?

**Comment by clobrano** [comment] 2019-09-15 12:49
Hi @memeplex, thanks for reporting the status. I replied directly on bugzilla, since I can reproduce the bug on latest Firefox with Fedora

**Comment by phaitonican** [comment] 2019-09-21 21:28
Found that `layers.acceleration.force-enabled` in `about:config` removes the white corners (for me) and also shows content with more than 60 FPS too

**Comment by clobrano** [comment] 2019-09-22 08:25
Indeed! Thanks for letting us know.
I don't know what this means, but I can report it on the original Firefox
ticket, thanks

**Comment by ongezoutenboter** [comment] 2020-01-14 15:08
> Found that `layers.acceleration.force-enabled` in `about:config` removes the white corners (for me) and also shows content with more than 60 FPS too

Thank you, thank you! Have been looking for this for ages.

**Comment by pkulak** [comment] 2020-02-08 21:09
Just gonna add that setting gfx.webrender.all = true took care of the issue for me.

**Comment by Feichtmeier** [comment] 2020-02-09 10:21
> > Found that `layers.acceleration.force-enabled` in `about:config` removes the white corners (for me) and also shows content with more than 60 FPS too
> 
> Thank you, thank you! Have been looking for this for ages.

wow this worked! @didrocks 
![image](https://user-images.githubusercontent.com/15329494/74100352-4ff11580-4b2e-11ea-9706-f874afdbf965.png)
